#  +---------------------------------------------------+
#  | +-----------------------------------------------+ |
#  | |      __  __       _____                       | |
#  | |     |  \/  |     |  __ \                      | |
#  | |     | \  / |_   _| |__) |__   ___  _ __       | |
#  | |     | |\/| | | | |  ___/ _ \ / _ \| '_ \      | |
#  | |     | |  | | |_| | |  | (_) | (_) | |_) |     | |
#  | |     |_|  |_|\__, |_|   \___/ \___/| .__/      | |
#  | |              __/ |                | |         | |
#  | |             |___/                 |_|         | |
#  | |                                               | |
#  | |                 by Spighetto                  | |
#  | +-----------------------------------------------+ |
#  +---------------------------------------------------+

# Set to true if you want to enable the updateChecker when server start/reload
updateChecker: true

poopSettings:
  # The trigger value shows how much value of hunger is needed to poop
  # For example one bread refills 5 food points
  # When player eats 8 bread the writing appears that he must poop
  trigger: 40
  # The limit value shows the max value of hunger not allowing the player to eat
  limit: 60
  # Note: if limit value is less than trigger, the plugin automatically get trigger value for both variables.


  # Time in seconds to des-pawn poop from ground
  delay: 5

  # Set it to true if you want the poop to have the display name of the player it matches (PlayerNick's Poop).
  # You can also choose the color of the writing with the minecraft color codes (Example &a for green or &b&l for blue and bold)
  namedPoop: true
  colorPoopName: "&6"
  # If "namedPoop" is false you can choose a display name of poop, leave "poopDisplayName" empty if you don't want it
  # You can also choose the color of the writing by adding the minecraft color codes (Example "&aPoop" for green or "&bMy &lPoop" for blue and bold)
  poopDisplayName: "&6Poop"

alerts:
  # Choose the phrase to send to the players, with colors too using &
  message: "&aYou have to poop"
  # Choose the phrase to send to the players when they reach the limit to eat
  messageAtLimit: "&aYou can't eat anymore, you have to poop first"
  # Choose where to show the phrase (Default 3):
  #  1 -> Chat
  #  2 -> Title
  #  3 -> Subtitle
  #  4 -> ActionBar
  wherePrint: 3

# -- Coming soon --
#growingSettings:
#  allCropsNearby: false
#  radius: 3
#  randomGrow: false

