name: MyPoop
version: 2.2.0
main: me.spighetto.mypoop.MyPoop
api-version: 1.19
authors: [Spighetto]
description: This plugin allows players to poop
commands:
  mypoop:
    description: General command for MyPoop plugin
    aliases: [myp]
